config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # /api/users/:id/follow
  namespace :api do
    post :upload_image, to: 'utils#upload_image'
    resources :users, only: [] do
      member do
        post :follow
      end
    end

    # /api/stories/20/bookmark
    # /api/stories/20/clap
    resources :stories, only: [] do
      member do
        post :clap
        post :bookmark
      end
    end
  end

  resources :users, only: [] do
    collection do
      get :pricing      # /users/pricing
      get :payment      # /users/payment
      post :pay         # /users/pay
    end
  end
  
  resources :stories do
    resources :comments, only: [:create]
  end

  # /@howhow/文章標題
  get '@:username/:story_id', to: 'pages#show', as: 'story_page'

  # /@howhow/
  get '@:username', to: 'pages#user', as: 'user_page'

  root 'pages#index'
  get '/demo', to: 'pages#demo'
end

app/views/shared/frontend/_flash.html.erb
<div class="notification is-primary">
  <%= notice %>
</div>

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class: 'navbar-item' do %>
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    <%  end %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>

          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              <%= content_tag :i, "", class: 'fas fa-crown has-text-primary' if current_user.vip_user? %> 

              <%= content_tag :i, "", class: 'fas fa-crown has-text-danger' if current_user.platinum_user? %> 

              <%= avatar(current_user, size: 50) %>
              <%= current_user.email %>
            </a>
    
            <div class="navbar-dropdown">
              <%= link_to '新增故事', new_story_path, class: 'navbar-item' %>
              <%= link_to '故事列表', stories_path, class: 'navbar-item' %>

              <%= link_to '會員升級', pricing_users_path, class: 'navbar-item' unless current_user.paid_user? %>
              <%= link_to '個人資料', edit_user_registration_path, class: 'navbar-item' %>
              <hr class="navbar-divider">
              <%= link_to '登出', destroy_user_session_path, class: 'navbar-item', method: 'delete', data: {confirm: '是否登出？'} %>
            </div>
          </div>
          <% else %>
            <%= link_to '註冊', new_user_registration_path, class: 'button is-primary' %>
            <%= link_to '登入', new_user_session_path, class: 'button is-light' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>