config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # /api/users/:id/follow
  namespace :api do
    post :upload_image, to: 'utils#upload_image'
    resources :users, only: [] do
      member do
        post :follow
      end
    end

    # /api/stories/20/bookmark
    # /api/stories/20/clap
    resources :stories, only: [] do
      member do
        post :clap
        post :bookmark
      end
    end
  end

  resources :users, only: [] do
    collection do
      get :pricing      # /users/pricing
      get :payment      # /users/payment
      post :pay         # /users/pay
    end
  end
  
  resources :stories do
    resources :comments, only: [:create]
  end

  # /@howhow/文章標題
  get '@:username/:story_id', to: 'pages#show', as: 'story_page'

  # /@howhow/
  get '@:username', to: 'pages#user', as: 'user_page'

  root 'pages#index'
  get '/demo', to: 'pages#demo'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: {
    user: 0,
    vip_user: 1,
    platinum_user: 2,
    admin: 3
  }

  # validtions
  validates :username, presence: true, uniqueness: true

  # relationships
  has_many :stories
  has_many :follows
  has_many :bookmarks
  has_one_attached :avatar

  # instance methods
  def paid_user?
    vip_user? or platinum_user?
  end

  def bookmark?(story)
    bookmarks.exists?(story: story)
  end

  def bookmark!(story)
    if bookmark?(story)
      bookmarks.find_by(story: story).destroy
      return "Unbookmarked"
    else
      bookmarks.create(story: story)
      return "Bookmarked"
    end
  end

  def follow?(user)
    follows.exists?(following: user)
  end

  def follow!(user)
    if follow?(user)
      follows.find_by(following: user).destroy
      return 'Follow'
    else
      follows.create(following: user)
      return 'Followed'
    end
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::BaseController
  before_action :find_user

  def follow
    render json: {status: current_user.follow!(@user)}
  end

  private
  def find_user
    @user = User.find(params[:id])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  private

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :intro, :avatar])
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def pricing
  end

  def payment
    @fee = ENV["price_#{params[:type]}"]
    @payment_type = (params[:type] == 'vip') ? 'VIP 會員' : '白金會員'
    @token = gateway.client_token.generate
  end

  def pay
    fee = ENV["price_#{params[:type]}"]
    nonce = params[:payment_nonce]

    result = gateway.transaction.sale(
      amount: fee,
      payment_method_nonce: nonce,
      options: {
        submit_for_settlement: true
      }
    )

    if result.success?
      current_user.send("#{params[:type]}_user!")   # meta programming   
      redirect_to root_path, notice: '付費成功'
    else
      redirect_to root_path, notice: '付費發生錯誤'
    end
  end

  private
  def gateway
    Braintree::Gateway.new(
      environment: :sandbox,
      merchant_id: ENV["braintree_merchant_id"],
      public_key: ENV["braintree_public_key"],
      private_key: ENV["braintree_private_key"],
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar(user, size: 250)
    image_tag user.avatar.variant(resize: "#{size}x#{size}"), class: 'user-avatar' if user.avatar.attached?
  end
end

app/views/users/payment.html.erb
<div class="box">
  <article class="media">
    <div class="media-left">
      <figure class="image is-64x64">
        <img src="https://fakeimg.pl/128x128/?text=CCH" alt="Image">
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <strong><%= @payment_type %></strong> <span>(USD <%= @fee %>)</span>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi, quas, illum inventore nemo quae minus vel itaque a laboriosam deleniti facere officiis consectetur omnis? Voluptates dignissimos ipsum illum non tempora.
        </p>
      </div>

      <%= form_with url: pay_users_path(type: params[:type]), id: 'pay_form', method: 'post', local: true do |form| %>

        <%= form.hidden_field :payment_nonce %>
        <div id="dropin-container"></div>
        <%= link_to '重新選擇方案', pricing_users_path, class: 'button is-light' %>
        <button id="submit-button" class="button is-danger">付錢去！</button>

      <% end %>



    </div>
  </article>
</div>


<script src="https://js.braintreegateway.com/web/dropin/1.20.4/js/dropin.min.js"></script>
<script>
  document.addEventListener('turbolinks:load', function(event) {
    var button = document.querySelector('#submit-button')
    let nonce_field = document.querySelector('input[name="payment_nonce"]')
    let form = document.querySelector('#pay_form')

    braintree.dropin.create({
      authorization: '<%= @token %>',
      container: '#dropin-container'
    }, function(createErr, instance) {
      button.addEventListener('click', function(event) {
        event.preventDefault()
        instance.requestPaymentMethod(function(err, payload) {
          nonce_field.value = payload.nonce
          form.submit()
          // submit payload.nonce to your server
        })
      })
    })
  })
</script>

app/views/users/pricing.html.erb
<section class="section">
  <div class="columns">
    <div class="column is-4 is-offset-2">
      <div class="card">
        <div class="card-image">
          <figure class="image is-4by3">
            <img src="https://fakeimg.pl/1280x960/?text=VIP" alt="Placeholder image">
          </figure>
        </div>
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-48x48">
                <img src="https://fakeimg.pl/96x96/?text=CCH" alt="Placeholder image">
              </figure>
            </div>
            <div class="media-content">
              <p class="title is-4">VIP 會員</p>
              <p class="subtitle is-6">USD <%= ENV['price_vip'] %></p>
            </div>
          </div>
          <div class="content">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi autem nostrum adipisci quas? 
          </div>
          <%= link_to '購買', payment_users_path(type: 'vip'), class: 'button is-danger is-fullwidth' %>
        </div>
      </div>
    </div>

    <div class="column is-4">
      <div class="card">
        <div class="card-image">
          <figure class="image is-4by3">
            <img src="https://fakeimg.pl/1280x860/?text=Platinum" alt="Placeholder image">
          </figure>
        </div>
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-48x48">
                <img src="https://fakeimg.pl/96x96/?text=CCH" alt="Placeholder image">
              </figure>
            </div>
            <div class="media-content">
              <p class="title is-4">白金會員</p>
              <p class="subtitle is-6">USD <%= ENV['price_platinum'] %></p>
            </div>
          </div>
          <div class="content">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi autem nostrum adipisci quas? 
          </div>
          <%= link_to '購買', payment_users_path(type: 'platinum'), class: 'button is-success is-fullwidth' %>
        </div>
      </div>
    </div>
  </div>
</section>