config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # /api/users/:id/follow
  namespace :api do
    post :upload_image, to: 'utils#upload_image'
    resources :users, only: [] do
      member do
        post :follow
      end
    end

    # /api/stories/20/bookmark
    # /api/stories/20/clap
    resources :stories, only: [] do
      member do
        post :clap
        post :bookmark
      end
    end
  end

  resources :users, only: [] do
    collection do
      get :pricing      # /users/pricing
      get :payment      # /users/payment
      post :pay         # /users/pay
    end
  end
  
  resources :stories do
    resources :comments, only: [:create]
  end

  # /@howhow/文章標題
  get '@:username/:story_id', to: 'pages#show', as: 'story_page'

  # /@howhow/
  get '@:username', to: 'pages#user', as: 'user_page'

  root 'pages#index'
  get '/demo', to: 'pages#demo'
end

app/views/pages/_comment.html.erb
<article class="comment">
  <span class="profile">
    <%= image_tag comment.user.avatar.variant(resize: '50x50'), class: 'comment-avatar' if comment.user.avatar.attached? %>
    <span class="username"><%= comment.user.username %></span>
  </span>
  <%= simple_format(comment.content) %>
</article>

app/views/pages/_comment_area.html.erb
<section class="comment-editor">
  <% if user_signed_in? %>
    <%= form_with model: comment, url: story_comments_path(story), class: 'comment_form', remote: true do |form| %>
      <%= form.text_area :content, rows: 5, class: 'textarea is-small' %>
      <%= form.button '送出', class: 'button is-primary is-fullwidth' %>
    <% end %>
  <% else %>
    <%= link_to '請先登入', new_user_session_path, class: 'button is-success' %>
    <%= link_to '會員註冊', new_user_registration_path, class: 'button is-info' %>
  <% end %>
</section>

app/views/pages/demo.html.erb
<div data-controller="demo">
  <input type="text" data-target="demo.content">
  <button data-action="click->demo#pushme">按我</button>
</div>

<div data-controller="demo">
  <input type="text" data-target="demo.content">
  <button data-action="click->demo#pushit">按它</button>
</div>

app/views/pages/index.html.erb
<h1 class="title">Hi</h1>

<section class="columns">
  <!-- left -->
  <section class="column">
    <article>
      <figure class="image">
        <img src="https://fakeimg.pl/350x150/f0f0f0" alt="">
      </figure>
      <h2 class="title is-5">Creating a Pipeline to True Workplace Diversity</h2>
      <p class="content">Providing resources, offering acceptance, and involving people of color are keys to making your company more divrse..</p>
      <footer>
        <p>Arielle Wiltz in Modus</p>
        <p>Aug 7</p>
      </footer>
    </article>
  </section>
  <!-- left -->
  <!-- middle -->
  <section class="column">
    <article class="media">
      <figure class="media-left">
        <img src="https://fakeimg.pl/100x100" alt="">
      </figure>
      <div class="media-content">
        <h2 class="title is-5">I Worked for an Amish Reality TV Show</h2>
        <footer>
          <p>Arielle Wiltz in Modus</p>
          <p>Aug 7</p>
        </footer>
      </div>
    </article>
    <article class="media">
      <figure class="media-left">
        <img src="https://fakeimg.pl/100x100" alt="">
      </figure>
      <div class="media-content">
        <h2 class="title is-5">I Worked for an Amish Reality TV Show</h2>
        <footer>
          <p>Arielle Wiltz in Modus</p>
          <p>Aug 7</p>
        </footer>
      </div>
    </article>
    <article class="media">
      <figure class="media-left">
        <img src="https://fakeimg.pl/100x100" alt="">
      </figure>
      <div class="media-content">
        <h2 class="title is-5">I Worked for an Amish Reality TV Show</h2>
        <footer>
          <p>Arielle Wiltz in Modus</p>
          <p>Aug 7</p>
        </footer>
      </div>
    </article>
  </section>
  <!-- middle -->
  <!-- right -->
  <section class="column">
    <article>
      <figure class="image">
        <img src="https://fakeimg.pl/350x200/f0f0f0" alt="">
      </figure>
      <h2 class="title is-5">I Worked for an Amish Reality TV Show</h2>
      <p class="content">Providing resources, offering acceptance, and involving people of color are keys to making your company more divrse..</p>
      <footer>
        <p>Arielle Wiltz in Modus</p>
        <p>Aug 7</p>
      </footer>
    </article>
  </section>
  <!-- right -->
</section>

<hr>

<section class="columns">
  <!-- article list -->
  <section class="column is-two-thirds">
    
    <% @stories.each do |story| %>
    <article class="media">
      <div class="media-content">
        <h2 class="title is-4"><%= link_to story.title, story_page_path(story.user.username, story), class: 'has-text-grey-dark' %></h2>
        <p class="content"><%= strip_tags(story.content).truncate(200) %></p>
        <footer>
          <p>
            <%= link_to story.user.username, user_page_path(story.user.username), class: 'has-text-grey-dark' %> | <%= time_ago_in_words(story.created_at) %>
          </p>
        </footer>
      </div>

      <% if story.cover_image.attached? %>
      <figure class="media-right">
        <%= image_tag story.cover_image.variant(resize: '150x150') %>
      </figure>
      <% end %>


    </article>
    <% end %>

  </section>
  <!-- article list -->

  <section class="column">
    <h2 class="title is-4">Popular on Medium</h2>
    <hr>
    
    <article class="media">
      <div class="media-left">01</div>
      <div class="media-content">
        <h3>Difficult Conversation Lessons From a Psychologist Who's Been Dealing With People</h3>
        <footer>
          <p>Thomas Oppong</p>
        </footer>
      </div>
    </article>

    <article class="media">
      <div class="media-left">01</div>
      <div class="media-content">
        <h3>Difficult Conversation Lessons From a Psychologist Who's Been Dealing With People</h3>
        <footer>
          <p>Thomas Oppong</p>
        </footer>
      </div>
    </article>

    <article class="media">
      <div class="media-left">01</div>
      <div class="media-content">
        <h3>Difficult Conversation Lessons From a Psychologist Who's Been Dealing With People</h3>
        <footer>
          <p>Thomas Oppong</p>
        </footer>
      </div>
    </article>

    <article class="media">
      <div class="media-left">01</div>
      <div class="media-content">
        <h3>Difficult Conversation Lessons From a Psychologist Who's Been Dealing With People</h3>
        <footer>
          <p>Thomas Oppong</p>
        </footer>
      </div>
    </article>

    <article class="media">
      <div class="media-left">01</div>
      <div class="media-content">
        <h3>Difficult Conversation Lessons From a Psychologist Who's Been Dealing With People</h3>
        <footer>
          <p>Thomas Oppong</p>
        </footer>
      </div>
    </article>
  </section>
</section>

app/views/pages/show.html.erb
<section class="columns has-text-centered story-content">
  <section class="column is-offset-3 is-6">
    <h1 class="title"><%= @story.title %></h1>
  
  <span class="profile" data-controller="user">
    <%= image_tag @story.user.avatar.variant(resize: '50x50'), class: 'avatar' if @story.user.avatar.attached? %>
    <span class="username"><%= @story.user.username %></span>
    <%= link_to '#', class: 'follow-button',
                     data: { action: 'user#follow',
                             user: @story.user.id,
                             target: 'user.followButton' } do %>
      <%= (user_signed_in? && current_user.follow?(@story.user)) ? 'Followed' : 'Follow' %>
    <% end %>

    <%= link_to '#', class: 'bookmark-button', data: { action: 'user#bookmark', slug: @story.slug } do %>
      <% if user_signed_in? && current_user.bookmark?(@story) %>
        <i class="fas fa-bookmark" data-user-target="bookmark"></i>
      <% else %>
        <i class="far fa-bookmark" data-user-target="bookmark"></i>
      <% end %>
    <% end %>
  </span>

  <article class="content">
    <%= image_tag @story.cover_image.variant(resize: '1000x500'), class: 'cover-image' if @story.cover_image.attached? %>
    <%= @story.content.html_safe %>

    <footer data-controller="story">
      <%= link_to '#', class: 'clapButton is-size-2 has-text-primary', data: { action: 'story#addClap', slug: @story.slug } do %>
        <i class="far fa-hand-spock"></i>
        <span class="clapCount" data-story-target="clapCount"><%= @story.clap %></span>
      <% end %>
    </footer>

  </article>
  <hr>
   <section class="comments">
    <h2>留言</h2>

      <%= render 'comment_area', story: @story, comment: @comment %>

      <section class="comment-list">
        
        <%= render partial: 'comment', collection: @comments %>

      </section>
   </section>
  </section>
</section>

app/views/pages/user.html.erb
<h1 class="title">user</h1>